apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    db: polar-postgres
data:
  init.sql: |
    CREATE DATABASE polardb_catalog;
    CREATE DATABASE polardb_order;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  labels:
    db: polar-rabbitmq
data:
  rabbitmq.conf: |
    default_user = user
    default_pass = password
    vm_memory_high_watermark.relative = 1.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: polar-backend
  labels:
    comp: polar-backend
spec:
  selector:
    matchLabels:
      comp: polar-backend
  template:
    metadata:
      labels:
        comp: polar-backend
    spec:
      containers:
        - name: catalog-service
          image: catalog-service
          ports:
            - protocol: TCP
              hostPort: 9001
              containerPort: 9001
          resources: {}
        - name: polar-postgres
          image: postgres:15.2
          ports:
            - protocol: TCP
              hostPort: 5432
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: postgres-config-volume
        - name: polar-redis
          image: redis:7.0
          ports:
            - protocol: TCP
              hostPort: 6379
              containerPort: 6379
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 100Mi
        - name: polar-rabbitmq
          image: rabbitmq:3.11-management
          ports:
            - protocol: TCP
              hostPort: 5672
              containerPort: 5672
            - protocol: TCP
              hostPort: 15672
              containerPort: 15672
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 150Mi
          volumeMounts:
            - mountPath: /etc/rabbitmq
              name: rabbitmq-config-volume
        - name: polar-keycloak
          image: quay.io/keycloak/keycloak:19.0
          args:
            - "start-dev"
          ports:
            - hostPort: 8080
              containerPort: 8080
          env:
            - name: KEYCLOAK_ADMIN
              value: user
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: password
            - name: JAVA_OPTS_APPEND
              value: "-Dkeycloak.import=/opt/keycloak/data/import/realm-config.json"
          resources:
            requests:
              cpu: 100m
              memory: 350Mi
            limits:
              cpu: 500m
              memory: 750Mi
          volumeMounts:
            - name: polar-keycloak-config-volume
              mountPath: /opt/keycloak/data/import
      volumes:
        - name: postgres-config-volume
          configMap:
            name: postgres-config
        - name: rabbitmq-config-volume
          configMap:
            name: rabbitmq-config
        - name: polar-keycloak-config-volume
          configMap:
            name: polar-keycloak
